config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jobs
  devise_for :users
  #root 'jobs#index'
  root 'pages#home'

  get "/pages/home" => "pages#home"
  get "/pages/quiz" => "pages#quiz" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  JOB_TYPES = ["Full-time", "Part-time", "Contract", "Freelance"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	render :layout => false
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /jobs
  # GET /jobs.json
  def index
    if(params.has_key?(:job_type))
      @jobs = Job.where(job_type: params[:job_type]).order("created_at desc")
    else
      @jobs = Job.all.order("created_at desc")
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  def trial
  end


  # GET /jobs/new
  def new
    @job = current_user.jobs.build
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.build(job_params)

    token = params[:stripeToken]
    job_type = params[:job_type]
    job_title = params[:title]
    card_brand = params[:user][:card_brand]
    card_exp_month = params[:user][:card_exp_month]
    card_exp_year  = params[:user][:card_exp_year]
    card_last4 = params[:user][:card_last4]

    charge = Stripe::Charge.create(
      :amount => 30000,
      :currency => "usd",
      :description => job_type,
      :statement_descriptor => job_title,
      :source => token
    )

    current_user.stripe_id = charge.id
    current_user.card_brand = card_brand
    current_user.card_exp_month = card_exp_month
    current_user.card_exp_year = card_exp_year
    current_user.card_last4 = card_last4
    #current_user.save!

    begin
      current_user.save!
      rescue ActiveRecord::RecordInvalid => invalid
      puts invalid.record.errors
    end


    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Your job listing was purchased successfully!' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end

    rescue Stripe::CardError => e
      flash.alert = e.message
      render action: :new
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :url, :job_type, :location, :job_author, :remote_ok, :apply_url, :avatar)
    end
end   

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
		render template: "pages/#{params[:page]}"
	end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  def job_type(job_type)
    if job_type == "Full-time"
      content_tag :span, "#{job_type}", class: "tag is-primary"
    elsif job_type == "Part-time"
      content_tag :span, "#{job_type}", class: "tag is-link"
    elsif job_type == "Freelance"
      content_tag :span, "#{job_type}", class: "tag is-warning"
    elsif job_type == "Contract"
      content_tag :span, "#{job_type}", class: "tag is-info"
    else
      ""
    end
  end

  def job_author(job)
    user_signed_in? && current_user.id == job.user_id
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<h1>Welcome to <%= Rails.configuration.application_name %>!</h1>
<p class="lead">Use this document as a way to quickly start any new project by generating files, installing gems, and more. </p>

app/views/jobs/_form.html.erb
<%= simple_form_for @job, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

      <div class="field">
        <div class="control">
        <%= f.input :title, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, placeholder: "Frontend Developer" %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :apply_url, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }  %>
        </div>
      </div>


    <div class="columns">
      <div class="field column is-4">
        <div class="control">
          <label class="label">Job Type:</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :job_type, collection: Job::JOB_TYPES, prompt: "Select a job type" %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-briefcase"></i>
            </span>
          </div>
        </div>
      </div>

      <div class="column">

        <div class="field">
          <div class="control">
            <%= f.input :location, require: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, hint: 'Examples: "Bengaluru/Bangalore", "Hyderbad", "Pune"' %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <label for="job[remote_ok]">
              <%= f.input :remote_ok, required: false, input_html: { class: "checkbox"}, wrapper: false, label: false %>
              Work can be done remotely
            </label><i class="fa fa-wifi"></i>
          </div>
        </div>
      </div>
    </div>

      <div class="field">
        <div class="control">
          <%= f.input :description, required: true, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" } %>
        </div>
      </div>


    <div class="columns">

      <div class="field column">
        <div class="control">
          <%= f.input :job_author, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, label: "Company" %>
        </div>
      </div>

      <div class="field column">
        <div class="control">
          <%= f.input :url, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, label: "Company Website", placeholder: "http://company.com" %>
        </div>
      </div>

    </div>



    <hr />

    <%= render 'payment' %>

    <%= f.button :submit, class: "button is-primary is-large is-rounded mv4" %>

<% end %>

app/views/jobs/_panel.html.erb
<nav class="panel">
  <p class="text-uppercase has-text-gray pv1 f6">filter by job type</p>

  <ul class="mb3 pa0">
      <%= link_to 'All', jobs_path, class: "button is-fullwidth is-dark" %>
 

      <%= link_to 'Full-time', jobs_path(job_type: "Full-time"), class: "button is-fullwidth is-primary" %>



      <%= link_to 'Part-time', jobs_path(job_type: "Part-time"), class: "button is-fullwidth is-link" %>



      <%= link_to 'Freelance', jobs_path(job_type: "Freelance"), class: "button is-fullwidth is-warning" %>



      <%= link_to 'Contract', jobs_path(job_type: "Contract"), class: "button is-fullwidth is-info" %>

  </ul>
</nav>

app/views/jobs/_payment.html.erb
<% if !@job.persisted? %>
  <h4 class="subtitle is-4">Payment</h4>

  <div class="notification is-light has-text-centered">
    <i class="fa fa-credit-card"></i>
    All jobs cost <strong>$300</strong> USD for 30 days.
    <span class="block mb4"></span>
  </div>

  <div class="form-row">
    <label for="card-element" class="label">
      Enter credit or debit card
    </label>

    <div id="card-element" class="form-control">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- used to display Element errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <% if current_user.stripe_id.present? %>
    <div class="last-card bg-light pa4 border-radius-3 mt4">
      <h5 class="is-6 title pt2">Previously used card</h5>
      <table class="table is-narrow bg-light is-fullwidth">
        <thead>
          <th>Card Brand</th>
          <th>Last 4 Digits</th>
          <th>Expiration Month</th>
          <th>Expiration Year</th>
        </thead>
        <tr>
          <td><%= current_user.card_brand %></td>
          <td><%= current_user.card_last4 %></td>
          <td><%= current_user.card_exp_month %></td>
          <td><%= current_user.card_exp_year %></td>
        </tr>
      </table>
    </div>
  <% end %>
<% end %>

app/views/jobs/edit.html.erb
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #133;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
</style>
</head>
<body>

<ul>  
  <li><%= link_to 'Show Navigation', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
</ul>

</body>





<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1 class="title is-3">Editing Job</h1>
        <%= render 'form', job: @job %>
      </div>
    </div>
  </div>
</section>

app/views/jobs/index.html.erb
<head>
<style>
ul {
    list-style-type: none;
    margin: 10;
    padding: 10;
    overflow: hidden;
    background-color: #a59c15;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
</style>
</head>
<body>

<ul>  
  <li><%= link_to 'Show Navigation', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
</ul>

</body>








<div class="columns border-top">

  <div class="column is-2 bg-light">
    <div class="pl3 pr1">
      <%= render 'panel' %>
    </div>
  </div>

  <div class="column is-9 pl6">
    <% @jobs.each do |job| %>
    <div class="columns border-bottom pt4">
      <div class="column is-1">
        <% if !job.avatar.file.nil? %>
          <%= link_to image_tag(job.avatar_url(:thumb), alt: job.job_author, width: 100, height: 100), job.url %>
        <% else %>
           <!--<%= link_to image_tag(("/assets/images/logo.png"), :alt => "LoGo", width: 100, height: 100), job.url %>  -->
           <%= link_to(image_tag("job-postings.png", :alt => "Logo")) %>
        <% end %>
      </div>
      <div class="column is-8">
        <h3 class="title is-4 index-title"><%= link_to job.title, job %></h3>
          
            <%= link_to job.job_author, job.url %>
          
        <div class="pv2 f6">
          <%= sanitize(job.description.truncate(200, separator: '</p>')) %>
        </div>

        <%= link_to 'View', job, class: 'button is-small is-link is-outlined' %>
        <% if current_user.try(:admin) || job_author(job) %>
            <p>Controls:</p>
            <%= link_to 'Edit', edit_job_path(job), class: 'button is-small is-link is-outlined' %>
            <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small is-link is-outlined' %>
        <% end %>

        </div>
        <div class="column has-text-right">
          <%= job_type(job.job_type) %>
          <p class="pt2 f6"><%= job.location %></p>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/jobs/new.html.erb
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #133;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
</style>
</head>


<body>
<ul>  
  <li><%= link_to 'Show Navigation', new_job_path, class: "navbar-item button is-primary is-rounded" %></li>
</ul>
</body>



<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1 class="title is-3">Post new Job</h1>
        <%= render 'form', job: @job %>
      </div>
    </div>
  </div>
</section>

app/views/jobs/show.html.erb
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #133;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
</style>
</head>
<body>

<ul>

  <!--    <li><%= link_to ' ', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>       -->

  

  <li><%= link_to 'Home Page', pages_home_path, class: "navbar-item button is-primary is-rounded" %></li>

  <li><%= link_to 'Jobs Board', jobs_path, class: "navbar-item button is-primary is-rounded" %></li>

  <li><%= link_to 'Post Job',  new_job_path, class: "navbar-item button is-primary is-rounded" %></li>
  <li><%= link_to 'Mock Test', pages_quiz_path, class: "navbar-item button is-danger is-rounded" %></li>


<% if user_signed_in? %>
    <div class="navbar-item has-dropdown is-hoverable">
        <li><%= link_to current_user.name, edit_user_registration_path, class: "navbar-item button is-danger is-rounded" %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-item button is-danger is-rounded" %><li>

    <% else %>

    <p class="control">
      <%= link_to "Sign In", new_user_session_path, class:"navbar-item button" %>
    </p>
    <p class="control">
      <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button"%>
    </p>
  <% end %>

  
  <!--    <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>
  <li><%= link_to ' ', jobs_path, class: "navbar-item button is-danger is-rounded" %></li>    -->



</ul>
</body>


<div class="columns pt4 pb7">
  <div class="column is-7 is-offset-1">

    <p class="f7"><i class="fa fa-clock"></i> Posted <%= time_ago_in_words(@job.created_at) %> ago</p>
    <h1 class="title is-2"><%= @job.title %></h1>

    
      <h1><%= job_type(@job.job_type) %></h1>
      <li class="inline-block f6 ph2"><i class="fa fa-pin"></i> <%= @job.location %></li>
      <% if @job.remote_ok? %>
      <li class="inline-block f6 ph2"><i class="fa fa-wifi"></i> Remote Job</li>
      <% end %>
    <hr>

    <div class="content text-serif f4">
      <%= @job.description.html_safe %>
    </div>

    <%= link_to 'Apply to this job', @job.apply_url, class:"button is-rounded is-large is-fullwidth is-link" %>

  </div>

  <div class="column is-2 is-offset-1 has-text-centered">

    <% if !@job.avatar.file.nil? %>
      <%= link_to image_tag(@job.avatar_url(:thumb), alt: @job.job_author, class: "has-text-centered"), @job.url %>
    <% end %>

    <h5 class="is-5 has-text-centered"><%= link_to @job.job_author, @job.url %></h5>

    <div class="mt2 mb4">
    <%= link_to @job.url do %>
      <i class="fa fa-globe"></i>
    <% end %>
    </div>

    <%= link_to 'Apply to this job', @job.apply_url, class:"button is-rounded is-fullwidth is-link" %>

    <% if current_user.try(:admin) || job_author(@job) %>
     
        <h5>Controls:</h5>
          <%= link_to 'View', @job, class: 'button is-small is-link is-outlined' %>

          <%= link_to 'Edit', edit_job_path(@job), class: 'button is-small is-link is-outlined' %>

          <%= link_to 'Delete', @job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small is-link is-outlined' %>
     
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', "https://js.stripe.com/v2/", "https://js.stripe.com/v3/", 'data-turbolinks-track': 'reload' %>

    <%= tag :meta, name: "stripe-public-key", content: Figaro.env.stripe_publishable_key %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

     <nav class="navbar app_menu" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5"><%= Rails.configuration.application_name %></h1>
        <% end  %>
        <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Home Page', pages_home_path, class: "navbar-item button is-primary is-rounded" %>
              </p>


            <p class="control">
              <%= link_to 'Post Job',  new_job_path, class: "navbar-item button is-primary is-rounded" %>
            </p>


            <% if user_signed_in? %>
            <p class="control">
              <%= link_to 'Mock Test', pages_quiz_path, class: "navbar-item button is-danger is-rounded" %>
            </p>

              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'User Profile', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>

            <% else %>

            <p class="control">
              <%= link_to 'Mock Test', new_user_session_path, class: "navbar-item button is-danger is-rounded" %>
            </p>

            <p class="control">
              <%= link_to "Sign In", new_user_session_path, class:"navbar-item button" %>
            </p>
            <p class="control">
              <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button"%>
            </p>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </nav>


  <%= yield %>

  <footer class="footer app_footer">
    <div class="container">
      <div class="content has-text-centered">
        <p>
        Site Developed and Maintained by <a href="https://www.google.co.in" target="_blank">Team VAGAA</a>. For more information, click here.
        </p>
      </div>
    </div>
  </footer>

  </body>
</html>

app/views/pages/about.html.erb
<p>
	Cupcake ipsum dolor sit amet danish. Marzipan I love toffee cupcake jujubes. Cheesecake cupcake I love icing cake lemon drops. Cake cake cupcake cupcake halvah sweet. Cheesecake candy pastry sweet roll caramels marzipan carrot cake halvah candy canes. Wafer gingerbread caramels cheesecake powder. Dragée donut lollipop cookie I love cake. Cookie caramels jujubes chupa chups. Tart pudding cotton candy topping macaroon I love jujubes I love. Pastry cotton candy I love gummies fruitcake. Fruitcake marshmallow I love I love tootsie roll lemon drops. Fruitcake bonbon caramels chocolate cake. Muffin pastry lemon drops macaroon icing cake icing.

Tart marshmallow lollipop. I love caramels lollipop wafer. Lollipop marzipan tiramisu muffin carrot cake cotton candy tootsie roll. Tart cake jujubes wafer. Danish cotton candy marshmallow jelly sweet roll biscuit jujubes cake. I love pastry toffee sesame snaps. Caramels tiramisu donut. Lollipop fruitcake pastry carrot cake macaroon powder wafer fruitcake. I love croissant pastry sugar plum. Lemon drops fruitcake caramels wafer donut topping jelly beans. Chocolate cake gingerbread croissant halvah jelly-o brownie I love gummies. I love donut cupcake gingerbread caramels.

Dragée muffin liquorice I love biscuit lemon drops. Oat cake marshmallow jujubes dragée cotton candy lemon drops jujubes topping powder. Cookie pie soufflé pudding wafer halvah. Candy canes marzipan oat cake candy canes cupcake donut halvah pastry tootsie roll. Gummi bears I love jelly-o chocolate cake powder marshmallow. Oat cake croissant apple pie toffee candy canes. Cotton candy croissant muffin jelly beans marshmallow. I love toffee toffee muffin cookie chocolate bar chocolate bar jelly fruitcake. Candy sweet roll tart chocolate candy canes muffin. I love icing caramels chocolate cake biscuit caramels dessert. Tart pastry tart I love carrot cake lollipop I love. Tart tart donut I love jelly beans candy. Ice cream pudding cupcake I love bonbon cupcake cotton candy danish. Soufflé fruitcake soufflé sesame snaps I love liquorice dessert marzipan sugar plum.

Topping dessert jelly beans halvah soufflé gingerbread tart cheesecake. Cake marzipan toffee pie dessert gingerbread sweet. Macaroon I love pudding jujubes. Apple pie bear claw tiramisu cake toffee wafer chupa chups I love biscuit. Apple pie I love I love sesame snaps macaroon tiramisu donut jujubes. Gummi bears topping apple pie lemon drops bonbon dessert. Candy canes lemon drops candy cake muffin. Donut cupcake I love dessert candy canes I love croissant jelly. Toffee sweet roll powder. Lemon drops I love marzipan. Pie dessert dessert donut tiramisu. Sweet roll I love chupa chups pastry pudding jujubes I love. Brownie pastry lemon drops caramels cheesecake danish. Soufflé brownie marshmallow dragée powder.

Pie halvah sweet roll caramels. Chocolate bar brownie bonbon donut cupcake pie topping tootsie roll. Cupcake cotton candy pudding topping cupcake pastry ice cream lemon drops. Icing powder gingerbread jujubes cookie biscuit fruitcake jujubes sugar plum. Donut lollipop bonbon halvah croissant brownie bonbon sugar plum. Chocolate I love tootsie roll gingerbread wafer pastry bear claw toffee. I love icing gummi bears cookie gingerbread I love donut cheesecake. Cake oat cake cheesecake I love. Jelly-o gummies cake jelly-o jelly beans pie. Gummies cotton candy ice cream bear claw jelly-o pudding. Dessert chupa chups jelly. I love caramels I love lollipop. Marzipan brownie gingerbread pie gummies marzipan. Lollipop sweet roll tiramisu.
</p>>

app/views/pages/quiz.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Quiz</title>
    
    <link rel="stylesheet" href="/assets/style.css">


    <%= javascript_include_tag 'app.js' %>
    <%= javascript_include_tag 'question.js' %>
    <%= javascript_include_tag 'quiz.js' %>
    
    <head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #133;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
</style>
</head>


<body>
<ul>  
  <li><%= link_to 'Show Navigation', new_job_path, class: "navbar-item button is-primary is-rounded" %></li>
</ul>
</body>





</head>
<body>
    <div class="grid">
        <div id="quiz">
            <h1>Mock</h1>
            <hr style="margin-bottom: 20px">

            <p id="question"></p>

            <div class="buttons">
                <button id="btn0"><span id="choice0"></span></button>
                <button id="btn1"><span id="choice1"></span></button>
                <button id="btn2"><span id="choice2"></span></button>
                <button id="btn3"><span id="choice3"></span></button>
            </div>

            <hr style="margin-top: 50px">
            <footer>
                <p id="progress">Question x of y</p>
            </footer>
        </div>
    </div>




</body>
</html>